# .profile

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# Load in the git branch prompt script.
source ~/.git-prompt.sh
#export GITAWAREPROMPT=~/.bash/git-aware-prompt
export GITAWAREPROMPT=~/Documents/personal/code/git-aware-prompt
source "${GITAWAREPROMPT}/main.sh"

# User specific aliases and functions

export PATH=~/bin:$PATH
export PS1='\[\e[32m\]\u\[\e[36m\]@\h \[\e[33m\]\w\[\e[0m\] \[$txtcyn\]$git_branch\[$txtred\]$git_dirty\[$txtrst\]\$ '
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad


# git aliases
alias gs='git status'
alias gc='git checkout'
alias gb='git branch'
alias gl='git lg'   # git config --global alias.lg "log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative"

git config --global alias.lg "log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative"
git config --global alias.ll "log --pretty=format:'%C(yellow)%h%Cred%d\\ %Creset%s%Cblue\\ [%cn]' --decorate --numstat"
git config --global alias.lds "log --pretty=format:'%C(yellow)%h\\ %ad%Cred%d\\ %Creset%s%Cblue\\ [%cn]' --decorate --date=short"
git config --global alias.ld "log --pretty=format:'%C(yellow)%h\\ %ad%Cred%d\\ %Creset%s%Cblue\\ [%cn]' --decorate --date=relative"
git config --global alias.cr "shortlog -sn"

# other aliases
alias ls='ls -G'
